### ISSUE TITLE
tabular data/ noisy instances/ new datasets

### ISSUE THREAD

**Issue by nazaretl** [RyanWangZf/Influence_Subsampling#3]
Hi,
thanks for sharing your implementation. I have some questions about it:

1.	Does it also work on tabular data?
2.	Is the code tailored to the datasets used in the paper or can one apply it to any data?
3.	Is it possible to identify the noisy instances (return the noisy IDs or the clean set)?

Thanks!

**Comment by RyanWangZf** [comment]
1&2: Yes, it works for any tabular data. Please refer to the notebook Demo_**.ipynb to see the input dataset format.

3: the noise degree is represented by `predicted_loss_diffs` in Demo_***.ipynb. To get the cleaned subsets, please refer to the sampling process executed in the notebook.

**Comment by nazaretl** [comment]
many thanks!
